routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('question', 'QuestionController');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
      protected $fillable = [
        'title', 'body', 'opt1', 'opt2', 'opt3', 'opt4', 'ans',
    ];

    protected $table = 'question';

     public static $create_validation_rules = [
	  	'title'=>'required',
	    'opt1'=>'required',
	    'opt2'=>'required',
	    'opt3'=>'required',
	    'opt4'=>'required'//,
	    //'ans'=>'required'
	  ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;


class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quest = Question::all();
        return view('question.index',compact('quest'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('question.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,Question::$create_validation_rules);
        $data = $request->only('title', 'body', 'opt1', 'opt2', 'opt3', 'opt4', 'ans');
        $question = Question::create($data);
        if($question)
        {
            $quest = Question::all();
            return redirect()->route('question.index',['quest' => $quest]);
        }
        else{
            return back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        return "Editing or deleting if Admin";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //
    }
}

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Break Interview | Question Bank</title>
	<link rel="stylesheet" href="{{ URL::asset('css/app.css') }}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>
<body>

<div class="container">
	@yield('content')
</div>
</body>
</html>

resources/views/question/create.blade.php
@extends('layouts.master')


@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Create Question</h3>
      <hr/>
      {!! Form::open(array('route'=>'question.store')) !!}
        <div class="form-group">
          {!! Form::label('title','Question Title') !!}
          {!! Form::text('title',null,array('class'=>'form-control','placeholder'=>'Question')) !!}
        </div>

        <div class="form-group">
          {!! Form::label('body','Question body') !!}
          {!! Form::text('body',null,array('class'=>'form-control','placeholder'=>'Body')) !!}
        </div>

        <div class="form-group">
          {!! Form::label('opt1','1st Option') !!}
          {!! Form::text('opt1',null,array('class'=>'form-control','placeholder'=>'1st Option')) !!}
        </div>

        <div class="form-group">
          {!! Form::label('opt2','2nd Option') !!}
          {!! Form::text('opt2',null,array('class'=>'form-control','placeholder'=>'2nd Option')) !!}
        </div>

        <div class="form-group">
          {!! Form::label('opt3','3rd Option') !!}
          {!! Form::text('opt3',null,array('class'=>'form-control','placeholder'=>'3rd Option')) !!}
        </div>

        <div class="form-group">
          {!! Form::label('opt4','4th Option') !!}
          {!! Form::text('opt4',null,array('class'=>'form-control','placeholder'=>'4th Option')) !!}
        </div>

        <div class="form-group">
          <label>Answer</label>
          <select class="form-control input-sm" name="ans" id="ans">
            <option value="">Select Answer</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
          </select>
        </div>

        <div class="form-group">
          {!! Form::token() !!}
          {!! Form::submit('Submit',array('class'=>'form-control btn btn-success')) !!}
        </div>

       
      {!! Form::close() !!}

@endsection

resources/views/question/index.blade.php
@extends('layouts.master')

@section('content')

  <hr>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    	@if( count($quest)===0)
    		No Question available.
    	@else
       <div >
      <div class="hidden">{{$count =1}} </div>
      @foreach($quest as $que)
        <div class = "panel panel-success">
         <div class = "panel-heading">
            <h3 class = "panel-title">Q.{{$count++ }}) {{ link_to_route('question.show',$que->title,array($que->id)) }}</h3>
         </div>
         
         <div class = "panel-body">
         @if(!($que->body == NULL))
           <div class = "well well-sm"> {{$que->body}}</div>
         @endif

          <fieldset id="{{$que->id}}">
        <div class="radio">
          <label><input type="radio" name="{{$que->id}}">{{$que->opt1}}</label>
        </div>
        <div class="radio">
          <label><input type="radio" name="{{$que->id}}">{{$que->opt2}}</label>
        </div>
        <div class="radio">
          <label><input type="radio" name="{{$que->id}}">{{$que->opt3}}</label>
        </div>
        <div class="radio">
          <label><input type="radio" name="{{$que->id}}">{{$que->opt4}}</label>
        </div>
        </fieldset>

      </div>
      
      </div>
      @endforeach
       <button class="form-control btn btn-success">Submit</button>
      @endif
    </div>
  </div>

@endsection